import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Categoria from '#models/categoria'

export default class CategoriaSeeder extends BaseSeeder {
    async run() {
        await Categoria.createMany([
            {
                nome: 'Ferramentas Manuais',
                descricao: 'Chaves, martelos, serras e outros itens essenciais para construções e reformas.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766774913/categorias/categorias/1.jpg',
                url: 'ferramentas-manuais',
                status: true,
            },
            {
                nome: 'Ferramentas Elétricas',
                descricao: 'Parafusadeiras, furadeiras, lixadeiras e mais para facilitar o trabalho.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766774948/categorias/categorias/2.jpg',
                url: 'ferramentas-eletricas',
                status: true,
            },
            {
                nome: 'Materiais de Construção',
                descricao: 'Cimento, areia, tijolos e materiais básicos para obra.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766774978/categorias/categorias/3.jpg',
                url: 'materiais-de-construcao',
                status: true,
            },
            {
                nome: 'Impermeabilizantes',
                descricao: 'Membranas e tintas para evitar infiltrações em obras.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766775013/categorias/categorias/4.jpg',
                url: 'impermeabilizantes',
                status: true,
            },
            {
                nome: 'Revestimentos',
                descricao: 'Pisos, azulejos e acabamentos para paredes e chão.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766775036/categorias/categorias/5.jpg',
                url: 'revestimentos',
                status: true,
            },
            {
                nome: 'Sistemas de Isolamento',
                descricao: 'Materiais para isolamento térmico e acústico.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766777786/categorias/categorias/6.jpg',
                url: 'sistemas-de-isolamento',
                status: true,
            },
            {
                nome: 'Fios e Cabos Elétricos',
                descricao: 'Cabos de energia e fios para instalações elétricas.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766777814/categorias/categorias/7.png',
                url: 'fios-e-cabos-eletricos',
                status: true,
            },
            {
                nome: 'Interruptores e Tomadas',
                descricao: 'Peças essenciais para controle e distribuição de energia.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766777929/categorias/categorias/8.png',
                url: 'interruptores-e-tomadas',
                status: true,
            },
            {
                nome: 'Lâmpadas e Luminárias',
                descricao: 'Lâmpadas LED, fluorescentes e luminárias para todos os ambientes.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766777975/categorias/categorias/9.png',
                url: 'lampadas-e-luminarias',
                status: true,
            },
            {
                nome: 'Disjuntores e Proteções',
                descricao: 'Disjuntores, fusíveis e dispositivos de proteção elétrica.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766778015/categorias/categorias/10.webp',
                url: 'disjuntores-e-protecoes',
                status: true,
            },
            {
                nome: 'Extensões e Adaptadores',
                descricao: 'Extensões elétricas, adaptadores e réguas de energia.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766778037/categorias/categorias/11.webp',
                url: 'extensoes-e-adaptadores',
                status: true,
            },
            {
                nome: 'Instalações de Energia Solar',
                descricao: 'Placas solares, inversores e baterias para energia limpa.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766778068/categorias/categorias/12.jpg',
                url: 'instalacoes-de-energia-solar',
                status: true,
            },
            {
                nome: 'Tubos e Conexões',
                descricao: 'Tubulações de PVC, cobre e conexões hidráulicas.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766778140/categorias/categorias/13.jpg',
                url: 'tubos-e-conexoes',
                status: true,
            },
            {
                nome: 'Acessórios Hidráulicos',
                descricao: 'Registros, válvulas, filtros e peças complementares.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766778227/categorias/categorias/14.jpg',
                url: 'acessorios-hidraulicos',
                status: true,
            },
            {
                nome: 'Bombas d\'Água',
                descricao: 'Bombas submersíveis e de pressão para diversas aplicações.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766778250/categorias/categorias/15.jpg',
                url: 'bombas-dagua',
                status: true,
            },
            {
                nome: 'Caixas D\'Água e Reservatórios',
                descricao: 'Soluções para armazenamento de água em obras.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766778283/categorias/categorias/16.jpg',
                url: 'caixas-dagua-e-reservatorios',
                status: true,
            },
            {
                nome: 'Sistemas de Irrigação',
                descricao: 'Aspersores, gotejadores e mangueiras para irrigação.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766778323/categorias/categorias/17.jpg',
                url: 'sistemas-de-irrigacao',
                status: true,
            },
            {
                nome: 'Tijolos e Pedras Ornamentais',
                descricao: 'Pedras naturais, mármores e tijolinhos decorativos.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766778350/categorias/categorias/18.jpg',
                url: 'tijolos-e-pedras-ornamentais',
                status: true,
            },
            {
                nome: 'Rodapés e Forros',
                descricao: 'Detalhes de acabamento para paredes e tetos.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766779858/categorias/categorias/19.webp',
                url: 'rodapes-e-forros',
                status: true,
            },
            {
                nome: 'Móveis para Construção e Decoração',
                descricao: 'Móveis planejados e decorativos para áreas construídas.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766779889/categorias/categorias/20.webp',
                url: 'moveis-para-construcao-e-decoracao',
                status: true,
            },
            {
                nome: 'Ferramentas de Jardinagem',
                descricao: 'Tesouras, pás, rastelos e itens para cuidar do jardim.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766779930/categorias/categorias/21.jpg',
                url: 'ferramentas-de-jardinagem',
                status: true,
            },
            {
                nome: 'Cercas e Alambrados',
                descricao: 'Cercas de madeira, metálicas e telas.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766779954/categorias/categorias/22.jpg',
                url: 'cercas-e-alambrados',
                status: true,
            },
            {
                nome: 'Segurança',
                descricao: 'Placas, cones e barreiras para obras e áreas de risco.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766779991/categorias/categorias/23.webp',
                url: 'sinalizacao-de-seguranca',
                status: true,
            },
            {
                nome: 'Câmeras de Segurança',
                descricao: 'Câmeras IP, sistemas de CFTV e kits de monitoramento.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766780116/categorias/categorias/24.jpg',
                url: 'cameras-de-seguranca',
                status: true,
            },
            {
                nome: 'Acessórios para Banheiro',
                descricao: 'Espelhos, duchas, box e metais sanitários.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766780194/categorias/categorias/25.webp',
                url: 'acessorios-para-banheiro',
                status: true,
            },
            {
                nome: 'Lixas e Escovas',
                descricao: 'Ferramentas para preparação e acabamento de superfícies.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766780224/categorias/categorias/26.webp',
                url: 'lixas-e-escovas',
                status: true,
            },
            {
                nome: 'Rolos e Pincéis',
                descricao: 'Rolos de pintura, pincéis e trinchas para aplicação de tintas.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766780245/categorias/categorias/27.jpg',
                url: 'rolos-e-pinceis',
                status: true,
            },
            {
                nome: 'Máquinas de Corte',
                descricao: 'Serras elétricas, cortadoras de concreto e similares.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766781388/categorias/categorias/28.webp',
                url: 'maquinas-de-corte',
                status: true,
            },
            {
                nome: 'Geradores e Compressores',
                descricao: 'Equipamentos de energia e pressão para uso em obras.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766781414/categorias/categorias/29.webp',
                url: 'geradores-e-compressores',
                status: true,
            },
            {
                nome: 'Pinos e Parafusos',
                descricao: 'Parafusos, porcas, pregos e fixadores diversos.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766781435/categorias/categorias/30.jpg',
                url: 'pinos-e-parafusos',
                status: true,
            },
            {
                nome: 'Portas',
                descricao: 'Portas de madeira, alumínio e aço.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766781454/categorias/categorias/31.jpg',
                url: 'portas',
                status: true,
            },
            {
                nome: 'Janelas',
                descricao: 'Janelas de madeira, alumínio e aço.',
                imagem: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1766781474/categorias/categorias/32.webp',
                url: 'janelas',
                status: true,
            },
        ])
    }
}