import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Endereco from '#models/enderecos'

export default class EnderecoSeeder extends BaseSeeder {
  async run() {
      await Endereco.createMany([
          {
              userId: 1,
              tipo: 'Casa',
              cep: '01001-000',
              estado: 'SP',
              cidade: 'São Paulo',
              bairro: 'Centro',
              rua: 'Rua A',
              numero: '123',
              complemento: 'Apto 1',
              ativo:true,
          },
          {
              userId: 2,
              tipo: 'Trabalho',
              cep: '20010-000',
              estado: 'RJ',
              cidade: 'Rio de Janeiro',
              bairro: 'Centro',
              rua: 'Avenida B',
              numero: '456',
              complemento: null,
              ativo: true,
          },
          {
              userId: 3,
              tipo: 'Casa',
              cep: '30110-000',
              estado: 'MG',
              cidade: 'Belo Horizonte',
              bairro: 'Savassi',
              rua: 'Rua C',
              numero: '789',
              complemento: 'Casa fundos',
              ativo: true,
          },
          {
              userId: 3,
              tipo: 'Trabalho',
              cep: '30110-001',
              estado: 'MG',
              cidade: 'Belo Horizonte',
              bairro: 'Funcionários',
              rua: 'Avenida D',
              numero: '101',
              complemento: null,
              ativo: true,
          },
          {
              userId: 4,
              tipo: 'Casa',
              cep: '40020-000',
              estado: 'BA',
              cidade: 'Salvador',
              bairro: 'Barra',
              rua: 'Rua E',
              numero: '202',
              complemento: 'Casa 2',
              ativo: true,
          },
          {
              userId: 5,
              tipo: 'Trabalho',
              cep: '50010-000',
              estado: 'PE',
              cidade: 'Recife',
              bairro: 'Boa Viagem',
              rua: 'Rua F',
              numero: '303',
              complemento: null,
              ativo: true,
          },
          {
              userId: 6,
              tipo: 'Casa',
              cep: '60020-000',
              estado: 'CE',
              cidade: 'Fortaleza',
              bairro: 'Meireles',
              rua: 'Avenida G',
              numero: '404',
              complemento: 'Apto 404',
              ativo: true,
          },
          {
              userId: 6,
              tipo: 'Trabalho',
              cep: '60020-001',
              estado: 'CE',
              cidade: 'Fortaleza',
              bairro: 'Aldeota',
              rua: 'Rua H',
              numero: '505',
              complemento: null,
              ativo: true,
          },
          {
              userId: 7,
              tipo: 'Casa',
              cep: '70040-000',
              estado: 'DF',
              cidade: 'Brasília',
              bairro: 'Asa Sul',
              rua: 'Rua I',
              numero: '606',
              complemento: 'Bloco B',
              ativo: true,
          },
          {
              userId: 8,
              tipo: 'Trabalho',
              cep: '80010-000',
              estado: 'PR',
              cidade: 'Curitiba',
              bairro: 'Centro',
              rua: 'Avenida J',
              numero: '707',
              complemento: null,
              ativo: true,
          },
      ])
  }
}