import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Produto from '#models/produto'

export default class ProdutoSeeder extends BaseSeeder {
    public async run() {
        await Produto.createMany([
            {
                nome: 'Martelo de Borracha',
                descricao: 'Martelo de borracha para uso em construções delicadas.',
                categoriaId: 1,
                marca: 'Construmax',
                atributos: { peso: '500g', cor: 'vermelho', garantia: '1 ano' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Parafusadeira Elétrica 12V',
                descricao: 'Parafusadeira com bateria recarregável e torque ajustável.',
                categoriaId: 2,
                marca: 'PowerTools',
                atributos: { voltagem: '12V', velocidade: '0-1500 rpm', peso: '1.5kg' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Saco de Cimento 50kg',
                descricao: 'Cimento Portland para obras gerais.',
                categoriaId: 3,
                marca: 'Cimento Forte',
                atributos: { peso: '50kg', tipo: 'Portland', validade: '6 meses' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Membrana Impermeabilizante Líquida',
                descricao: 'Produto para impermeabilização de lajes e paredes.',
                categoriaId: 4,
                marca: 'Impermeex',
                atributos: { rendimento: '2m²/litro', cor: 'cinza', garantia: '2 anos' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Piso Cerâmico 45x45',
                descricao: 'Piso cerâmico para áreas internas e externas.',
                categoriaId: 5,
                marca: 'Cerâmica Bela',
                atributos: { tamanho: '45x45 cm', cor: 'bege', tipo: 'antiderrapante' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Lã de Vidro 50mm',
                descricao: 'Material para isolamento térmico e acústico.',
                categoriaId: 6,
                marca: 'Isolamax',
                atributos: { espessura: '50mm', comprimento: '10m', largura: '1.2m' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Cabo Elétrico 2,5mm²',
                descricao: 'Cabo para instalações elétricas residenciais.',
                categoriaId: 7,
                marca: 'Eletricom',
                atributos: { bitola: '2,5mm²', cor: 'preto', rolo: '100m' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Interruptor Simples',
                descricao: 'Interruptor para iluminação residencial.',
                categoriaId: 8,
                marca: 'Eletricom',
                atributos: { cor: 'branco', amperagem: '10A', tipo: 'simples' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Lâmpada LED 9W',
                descricao: 'Lâmpada LED econômica para uso residencial.',
                categoriaId: 9,
                marca: 'Lumina',
                atributos: { potencia: '9W', cor: 'branco frio', vida_util: '15000h' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Disjuntor Bipolar 40A',
                descricao: 'Disjuntor para proteção de circuitos elétricos.',
                categoriaId: 10,
                marca: 'Segurmax',
                atributos: { amperagem: '40A', polos: 2, tipo: 'bipolar' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Extensão Elétrica 5m',
                descricao: 'Extensão com 3 tomadas e cabo resistente.',
                categoriaId: 11,
                marca: 'Powerext',
                atributos: { comprimento: '5m', tomadas: 3, cabo: '2,0mm²' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Painel Solar 330W',
                descricao: 'Painel solar para geração de energia limpa.',
                categoriaId: 12,
                marca: 'Solarmax',
                atributos: { potencia: '330W', dimensoes: '1,7x1m', garantia: '10 anos' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Tubo PVC 100mm',
                descricao: 'Tubo para instalações hidráulicas.',
                categoriaId: 13,
                marca: 'HidraPlus',
                atributos: { diametro: '100mm', comprimento: '3m', cor: 'branco' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Registro de Gaveta',
                descricao: 'Registro para controle de fluxo em tubulações.',
                categoriaId: 14,
                marca: 'VálvulaTech',
                atributos: { material: 'latão', tamanho: '1/2"', tipo: 'gaveta' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Bomba Submersível 1/2 HP',
                descricao: 'Bomba para uso residencial e industrial.',
                categoriaId: 15,
                marca: 'PumpTech',
                atributos: { potencia: '1/2 HP', vazao: '4000 L/h', tensao: '220V' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Caixa D\'Água 1000L',
                descricao: 'Reservatório para armazenamento de água.',
                categoriaId: 16,
                marca: 'Reservamax',
                atributos: { capacidade: '1000L', material: 'polietileno', cor: 'azul' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Aspersor de Jardim',
                descricao: 'Aspersor para sistemas de irrigação residencial.',
                categoriaId: 17,
                marca: 'IrrigaPro',
                atributos: { alcance: '10m', tipo: 'rotativo', conexao: '3/4"' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Tijolo Maciço',
                descricao: 'Tijolo para alvenaria estrutural.',
                categoriaId: 18,
                marca: 'Construtijolo',
                atributos: { dimensoes: '20x10x5cm', peso: '3kg', resistencia: '15MPa' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Rodapé MDF 7cm',
                descricao: 'Rodapé para acabamento de paredes.',
                categoriaId: 19,
                marca: 'Acabamax',
                atributos: { altura: '7cm', cor: 'branco', material: 'MDF' },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
            {
                nome: 'Armário Planejado Cozinha',
                descricao: 'Armário para cozinha com acabamento em MDF.',
                categoriaId: 20,
                marca: 'DecoraFácil',
                atributos: { material: 'MDF', cor: 'carvalho', portas: 4 },
                peso: 2.5,
                dimensoes: { altura: 20, largura: 10, profundidade: 30 },
            },
        ])
    }
}
