import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Usuarios from '#models/usuarios';

export default class UsuarioSeeder extends BaseSeeder {
    public async run() {
        await Usuarios.createMany([
            {
                nomeCompleto: 'Otávio Faria Fagundes',
                email: 'otaviofariafagunde1@gmail.com',
                cpf: '04703053047',
                senha: '1',
                telefone: '53991946000',
                dt_nasc: new Date('2003-10-13'),
                status: '1',
                img_user: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1776103299/usuarios/usuarios/1.jpg',
                email_verificado: true,
                stripeCustomerId: 'cus_UxXP7bCEPaskhw'
            },
            {
                nomeCompleto: 'João Silva',
                email: 'joao.silva@example.com',
                cpf: '12345678901',
                senha: 'senha123',
                telefone: '11999999999',
                dt_nasc: new Date('1985-01-15'),
                status: '1',
                email_verificado: true,
            },
            {
                nomeCompleto: 'Maria Oliveira',
                email: 'maria.oliveira@example.com',
                cpf: '23456789012',
                senha: 'senha123',
                telefone: '21988888888',
                dt_nasc: new Date('1990-03-20'),
                status: '1',
                email_verificado: true,
            },
            {
                nomeCompleto: 'Carlos Pereira',
                email: 'carlos.pereira@example.com',
                cpf: '34567890123',
                senha: 'senha123',
                telefone: '31977777777',
                dt_nasc: new Date('1982-07-10'),
                status: '1',
                email_verificado: true,
            },
            {
                nomeCompleto: 'Ana Costa',
                email: 'ana.costa@example.com',
                cpf: '45678901234',
                senha: 'senha123',
                telefone: '41966666666',
                dt_nasc: new Date('1988-11-30'),
                status: '1',
                email_verificado: true,
            },
            {
                nomeCompleto: 'Pedro Almeida',
                email: 'pedro.almeida@example.com',
                cpf: '56789012345',
                senha: 'senha123',
                telefone: '51955555555',
                dt_nasc: new Date('1975-09-05'),
                status: '1',
                email_verificado: true,
            },
            {
                nomeCompleto: 'Luciana Santos',
                email: 'luciana.santos@example.com',
                cpf: '67890123456',
                senha: 'senha123',
                telefone: '61944444444',
                dt_nasc: new Date('1995-12-12'),
                status: '1',
                email_verificado: true,
            },
            {
                nomeCompleto: 'Ricardo Lima',
                email: 'ricardo.lima@example.com',
                cpf: '78901234567',
                senha: 'senha123',
                telefone: '71933333333',
                dt_nasc: new Date('1980-06-22'),
                status: '1',
                email_verificado: true,
            },
            {
                nomeCompleto: 'Patrícia Rodrigues',
                email: 'patricia.rodrigues@example.com',
                cpf: '89012345678',
                senha: 'senha123',
                telefone: '81922222222',
                dt_nasc: new Date('1992-02-14'),
                status: '1',
                email_verificado: true,
            },
            {
                nomeCompleto: 'Bruno Ferreira',
                email: 'bruno.ferreira@example.com',
                cpf: '90123456789',
                senha: 'senha123',
                telefone: '91911111111',
                dt_nasc: new Date('1987-04-28'),
                status: '1',
                email_verificado: true,
            },
            {
                nomeCompleto: 'Fernanda Souza',
                email: 'fernanda.souza@example.com',
                cpf: '01234567890',
                senha: 'senha123',
                telefone: '99999999999',
                dt_nasc: new Date('1991-08-19'),
                status: '1',
                email_verificado: true,
            },
        ])
    }
}
