import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Vendedor from '#models/vendedores'

export default class VendedorSeeder extends BaseSeeder {
    public async run() {
        await Vendedor.createMany([
            {
                userId: 1,
                nomeLoja: 'Construtech Materiais',
                cnpj: '12.345.678/0001-01',
                descricaoLoja: 'Loja especializada em materiais de construção e ferramentas.',
                email: 'contato@construtech.com',
                telefone: '11999998888',
                categoria: 'Materiais',
                cep: '01001-000',
                estado: 'SP',
                cidade: 'São Paulo',
                bairro: 'Centro',
                rua: 'Rua1',
                numero: '100',
                avaliacaoMedia: 4.75,
                status: '1',
                imgVendedor: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1776104287/vendedores/vendedor/1.jpg',
                stripeAccountId: 'acct_1TxeHRADZCeklv4e',
                stripeOnboardingCompleted: true,
                stripeChargesEnabled: true,
                stripePayoutsEnabled: true,
            },
            {
                userId: 2,
                nomeLoja: 'Ferragens Rio',
                cnpj: '23.456.789/0001-02',
                descricaoLoja: 'Ferragens e acessórios para construções e reformas.',
                email: 'vendas@ferragensrio.com',
                telefone: '21988887777',
                categoria: 'Ferragens',
                cep: '20010-000',
                estado: 'RJ',
                cidade: 'Rio de Janeiro',
                bairro: 'Centro',
                rua: 'Rua2',
                numero: '200',
                avaliacaoMedia: 4.50,
                status: '1',
                stripeAccountId: 'acct_1U5ZSmAEzscgMyPR',
                stripeOnboardingCompleted: true,
                stripeChargesEnabled: true,
                stripePayoutsEnabled: true,
            },
            {
                userId: 3,
                nomeLoja: 'Tijolos BH',
                cnpj: '34.567.890/0001-03',
                descricaoLoja: 'Fornecedor de tijolos e blocos para obras de todos os portes.',
                email: 'contato@tijolosbh.com',
                telefone: '31977776666',
                categoria: 'Materiais',
                cep: '30110-000',
                estado: 'MG',
                cidade: 'Belo Horizonte',
                bairro: 'Savassi',
                rua: 'Rua3',
                numero: '300',
                avaliacaoMedia: 4.30,
                status: '1',
            },
            {
                userId: 4,
                nomeLoja: 'Martelos & Cia',
                cnpj: '45.678.901/0001-04',
                descricaoLoja: 'Ferramentas manuais de alta qualidade para profissionais.',
                email: 'contato@martelosecia.com',
                telefone: '41966665555',
                categoria: 'Ferramentas',
                cep: '40020-000',
                estado: 'BA',
                cidade: 'Salvador',
                bairro: 'Barra',
                rua: 'Rua4',
                numero: '400',
                avaliacaoMedia: 4.60,
                status: '1',
            },
            {
                userId: 5,
                nomeLoja: 'Reformas Recife',
                cnpj: '56.789.012/0001-05',
                descricaoLoja: 'Tudo para reformas residenciais e comerciais.',
                email: 'vendas@reformasrecife.com',
                telefone: '51955554444',
                categoria: 'Reformas',
                cep: '50010-000',
                estado: 'PE',
                cidade: 'Recife',
                bairro: 'Boa Viagem',
                rua: 'Rua5',
                numero: '500',
                avaliacaoMedia: 4.10,
                status: '1',
                imgVendedor: 'https://res.cloudinary.com/dapcd8spu/image/upload/v1776104430/vendedores/vendedor/5.jpg',
            },
            {
                userId: 6,
                nomeLoja: 'Cerâmica Fortaleza',
                cnpj: '67.890.123/0001-06',
                descricaoLoja: 'Cerâmicas e revestimentos para construção civil.',
                email: 'contato@ceramicafortaleza.com',
                telefone: '61944443333',
                categoria: 'Revestimentos',
                cep: '60020-000',
                estado: 'CE',
                cidade: 'Fortaleza',
                bairro: 'Meireles',
                rua: 'Rua6',
                numero: '600',
                avaliacaoMedia: 4.20,
                status: '1',
            },
            {
                userId: 7,
                nomeLoja: 'Tintas Brasília',
                cnpj: '78.901.234/0001-07',
                descricaoLoja: 'Tintas e produtos para pintura residencial e industrial.',
                email: 'contato@tintasbrasilia.com',
                telefone: '71933332222',
                categoria: 'Tintas',
                cep: '70040-000',
                estado: 'DF',
                cidade: 'Brasília',
                bairro: 'Asa Sul',
                rua: 'Rua7',
                numero: '700',
                avaliacaoMedia: 4.55,
                status: '1',
            },
            {
                userId: 8,
                nomeLoja: 'Vidros Curitiba',
                cnpj: '89.012.345/0001-08',
                descricaoLoja: 'Fornecimento e instalação de vidros para construção civil.',
                email: 'vendas@vidroscuritiba.com',
                telefone: '81922221111',
                categoria: 'Vidros',
                cep: '80010-000',
                estado: 'PR',
                cidade: 'Curitiba',
                bairro: 'Centro',
                rua: 'Rua8',
                numero: '800',
                avaliacaoMedia: 4.40,
                status: '1',
            },
            {
                userId: 9,
                nomeLoja: 'Elétrica Porto Alegre',
                cnpj: '90.123.456/0001-09',
                descricaoLoja: 'Produtos elétricos e acessórios para instalações.',
                email: 'contato@eletricaportoalegre.com',
                telefone: '91911110000',
                categoria: 'Elétrica',
                cep: '90010-000',
                estado: 'RS',
                cidade: 'Porto Alegre',
                bairro: 'Centro Histórico',
                rua: 'Rua9',
                numero: '900',
                avaliacaoMedia: 4.35,
                status: '1',
            },
            {
                userId: 10,
                nomeLoja: 'Pisos Manaus',
                cnpj: '01.234.567/0001-10',
                descricaoLoja: 'Pisos e revestimentos para obras residenciais e comerciais.',
                email: 'vendas@pisosmanaus.com',
                telefone: '92999998888',
                categoria: 'Pisos',
                cep: '69010-000',
                estado: 'AM',
                cidade: 'Manaus',
                bairro: 'Centro',
                rua: 'Rua10',
                numero: '1000',
                avaliacaoMedia: 4.50,
                status: '1',
            },
        ])
    }
}
